apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    vault.hashicorp.com/agent-inject: {{ .Values.metadata.annotations.vault }}
    vault.hashicorp.com/agent-inject-secret-webapp: {{ .Values.metadata.annotations.secret }}
    vault.hashicorp.com/role: {{ .Values.metadata.annotations.role }}
  labels:
    environment: {{ .Values.metadata.labels.environment }}
spec:
  image: {{ .Values.image.repository }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  flinkConfig:
    taskmanager.heap.size: {{ .Values.flinkConfig.heap }}
    taskmanager.network.memory.fraction: {{ .Values.flinkConfig.fraction }}
    taskmanager.network.memory.min: {{ .Values.flinkConfig.min }}
    state.backend.fs.checkpointdir: {{ .Values.flinkConfig.backend }}
    state.checkpoints.dir: {{ .Values.flinkConfig.checkpoint }}
    state.savepoints.dir: {{ .Values.flinkConfig.savepoint }}
    web.upload.dir: {{ .Values.flinkConfig.upload }}
  jobManagerConfig:
    resources:
      requests:
        memory: {{ .Values.jobManager.resources.requests.memory }}
        cpu: {{ .Values.jobManager.resources.requests.cpu }}
    replicas: {{ .Values.jobManager.replicas }}
  taskManagerConfig:
    taskSlots: {{ .Values.taskManager.taskSlots }}
    resources:
      requests:
        memory: {{ .Values.taskManager.resources.requests.memory }}
        cpu: {{ .Values.taskManager.resources.requests.cpu }}
  restartNonce: {{ .Values.restartNonce }}
  flinkVersion: {{ .Values.flinkVersion }}
  jarName: {{ .Values.jarName }}
  parallelism: {{ .Values.parallelism }}
  entryClass: {{ .Values.entryClass }}
