apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    vault.hashicorp.com/agent-inject: {{ .Values.metadata.annotations.vault }}
    vault.hashicorp.com/agent-inject-secret-webapp: {{ .Values.metadata.annotations.secret }}
    vault.hashicorp.com/role: {{ .Values.metadata.annotations.role }}
  labels:
    environment: {{ .Values.metadata.labels.environment }}
spec:
  image: {{ .Values.spec.image }}
  flinkConfig:
    jobmanager.web.submit.enable: true
    taskmanager.heap.size: {{ .Values.spec.flinkConfig.heap }}
    taskmanager.network.memory.fraction: {{ .Values.spec.flinkConfig.fraction }}
    taskmanager.network.memory.min: {{ .Values.spec.flinkConfig.min }}
    state.backend.fs.checkpointdir: {{ .Values.spec.flinkConfig.backend }}
    state.checkpoints.dir: {{ .Values.spec.flinkConfig.checkpoint }}
    state.savepoints.dir: {{ .Values.spec.flinkConfig.savepoint }}
    web.upload.dir: /opt/flink
  jobManagerConfig:
    nodeSelector:
      nodeLabel: node1
    resources:
      requests:
        memory: {{ .Values.spec.jobManager.resources.requests.memory }}
        cpu: {{ .Values.spec.jobManager.resources.requests.cpu }}
    replicas: {{ .Values.spec.jobManager.replicas }}
  taskManagerConfig:
    nodeSelector:
      nodeLabel: node4
    taskSlots: {{ .Values.spec.taskManager.taskSlots }}
    resources:
      requests:
        memory: {{ .Values.spec.taskManager.resources.requests.memory }}
        cpu: {{ .Values.spec.taskManager.resources.requests.cpu }}
  restartNonce: {{ .Values.spec.restartNonce }}
  flinkVersion: "1.9"
  jarName: {{ .Values.spec.jarName }}
  parallelism: {{ .Values.spec.parallelism }}
  entryClass: {{ .Values.spec.entryClass }}
  programArgs: "--config.file /var/config.yaml"
